INSERT INTO EMPLOYEE (ID, NAME, ROL_POSITION, GENDER, HAS_COURSES) VALUES (1, 'Nuevo empleado', 'Administrativo', 'Male', TRUE);

INSERT INTO COURSE (ID, NAME) VALUES (1, 'Inducción');
INSERT INTO COURSE (ID, NAME) VALUES (2, 'Seguridad');
INSERT INTO COURSE (ID, NAME) VALUES (3, 'Normativa');
INSERT INTO COURSE (ID, NAME) VALUES (4, 'Valores institucionales');
INSERT INTO COURSE (ID, NAME) VALUES (5, 'Terminología');

INSERT INTO COURSES_BY_EMPLOYEE (EMPLOYEE_ID, COURSE_ID) VALUES (1, 5)
